### PR TITLE
Add submitGarantee method to SignifydAPI

### PR DESCRIPTION
**Pull request by pedrocasado**
Add submitGarantee method to SignifydAPI

### CODE REVIEW

**Comment by pedrocasado** [comment]
@chrismorris528, would you be able to merge my PR and release version 0.1.7?

**Comment by chrismorris528** [comment]
Yes, having the team look at this.

**Comment by chrismorris528** [comment]
Should have a commit for this soon, just finishing some testing.

**Comment by chrismorris528** [comment]
We added this method along with cancel guarantee to the latest release.

**Pull request closed without merging**
