### PR TITLE
Get an error message when a request fails

### PR DESCRIPTION
**Pull request by Korri**
Added a `getLastErrorMessage` to get some information on what failed other then the default `false` return value.

So you can do somthing like that now:

```php
$case = $apiInstance->getCase(44);
if($case === false) {
    throw new Exception('Case retrieval failed: ' . $apiInstance->getLastErrorMessage());
}
...
```

### CODE REVIEW

**Comment by janhartigan** [comment]
Is there any plan to merge this in? We would like to use this in our implementation.

**Comment by chrismorris528** [comment]
@janhartigan We like the suggestion and decided to make some improvements to what was suggested. This will be pushed to the master branch. We will close this request once master is updated.

**Comment by janhartigan** [comment]
Great that's good to hear.

**Comment by Korri** [comment]
@chrismorris528 any news on this feature?

**Comment by chrismorris528** [comment]
@Korri this feature is slated for our next sprint. It should be ready sometime in the next couple of weeks.

**Comment by chrismorris528** [comment]
@Korri we plan to have a release this week with this feature included.

**Comment by chrismorris528** [comment]
This is in 1.1.2 thanks for your patience

**Pull request closed without merging**
